users = "users"
spamers = "spamers"
messages_to_check_on_spam ="messages_to_check_on_spam"
blocked_messages = "blocked_messages"
completed_messages = "completed_messages"
readed_messages ="readed_messages"
messages = "messages"
messages_to_check="messages_to_check"  
log_events = "log_events"
active_users = "active_users"
userMode =["send message","read message","messages are checking for spam","messages are blocked due to spam","exit"]
adminMode =["log events","online users","active users","active spamers","exit"]
startMenu = ['Admin','Simple User','Worker','exit']
